// Package playback provides terminal recording playback functionality.
// It supports both macOS and Linux script command output formats.
package playback

// Frame represents a single frame of terminal content at a specific timestamp.
// For static playback, use a single frame with Timestamp 0.
// For animated playback, use multiple frames with increasing timestamps.
type Frame struct {
	Timestamp float64 `json:"timestamp"` // Time in seconds (cumulative from start)
	Content   string  `json:"content"`   // Terminal content (with ANSI codes preserved)
}

// FooterLink represents a link to display in the footer alongside record-tui attribution.
type FooterLink struct {
	Text string // Display text (e.g., "swe-swe")
	URL  string // Link URL (e.g., "https://github.com/choonkeat/swe-swe")
}

// Options configures HTML rendering behavior.
type Options struct {
	Title      string     // Page title (defaults to "Terminal" if empty)
	FooterLink FooterLink // Optional co-branding link in footer (e.g., "generated by record-tui x swe-swe")
	TOC        []TOCEntry // Optional table-of-contents entries for navigation
}

// StreamingOptions configures streaming HTML rendering behavior.
// Use this for large terminal recordings where embedding data in HTML causes slow loading.
// The generated HTML fetches session data from DataURL and streams it to xterm.js.
type StreamingOptions struct {
	Title      string     // Page title (defaults to "Terminal" if empty)
	DataURL    string     // URL to fetch session data from (e.g., "./session.log", "/api/recording/123")
	FooterLink FooterLink // Optional co-branding link in footer
	Cols       uint16     // Terminal columns (0 = auto-detect, default 240)
	MaxRows    uint32     // Maximum initial rows before auto-resize (0 = default 100000)
	TOC        []TOCEntry // Optional table-of-contents entries for navigation
}

// TOCEntry represents a navigation point in the terminal recording.
// Each entry corresponds to a user command identified from the timing file.
type TOCEntry struct {
	Label string `json:"label"` // What the user typed (e.g., "npm test")
	Line  int    `json:"line"`  // Line number in the output (0-indexed)
}
