// Package playback provides terminal recording playback functionality.
// It supports both macOS and Linux script command output formats.
package playback

// Frame represents a single frame of terminal content at a specific timestamp.
// For static playback, use a single frame with Timestamp 0.
// For animated playback, use multiple frames with increasing timestamps.
type Frame struct {
	Timestamp float64 `json:"timestamp"` // Time in seconds (cumulative from start)
	Content   string  `json:"content"`   // Terminal content (with ANSI codes preserved)
}

// FooterLink represents a link to display in the footer alongside record-tui attribution.
type FooterLink struct {
	Text string // Display text (e.g., "swe-swe")
	URL  string // Link URL (e.g., "https://github.com/choonkeat/swe-swe")
}

// Options configures HTML rendering behavior.
type Options struct {
	Title      string     // Page title (defaults to "Terminal" if empty)
	FooterLink FooterLink // Optional co-branding link in footer (e.g., "generated by record-tui x swe-swe")
}

// StreamingOptions configures streaming HTML rendering behavior.
// Use this for large terminal recordings where embedding data in HTML causes slow loading.
// The generated HTML fetches session data from DataURL and streams it to xterm.js.
type StreamingOptions struct {
	Title      string     // Page title (defaults to "Terminal" if empty)
	DataURL    string     // URL to fetch session data from (e.g., "./session.log", "/api/recording/123")
	FooterLink FooterLink // Optional co-branding link in footer
}
